version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm i
      - run: npm lint-ci
      - run: npm test
workflows:
  version: 2
  test:
    jobs:
      - test