version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
      - image: redis:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint-ci
      - run: npm test
workflows:
  version: 2
  test:
    jobs:
      - test